/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1.newpackage;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Marius
 */
public class Home extends javax.swing.JFrame {
    
    private boolean isRunTestClicked       = false;
    private boolean isConfigureTestClicked = false;
    private boolean isUploadScoreClicked   = false;
    private boolean isHelpClicked          = false;
    public  boolean results                = false;
    
    int xx;
    int xy;
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        rb_Sequential.setSelected(true);
       // this.setExtendedState(ICONIFIED);
        //this.setExtendedState(JFrame.ICONIFIED);﻿
      //  jButton1.addActionListener(this.);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_ConfigureTest = new javax.swing.JLabel();
        lbl_RunTest = new javax.swing.JLabel();
        lbl_UploadScore = new javax.swing.JLabel();
        lbl_Help = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ConfigureTest = new javax.swing.JPanel();
        rb_RandomAccess = new javax.swing.JRadioButton();
        rb_Sequential = new javax.swing.JRadioButton();
        lbl_RandomAccess = new javax.swing.JLabel();
        lbl_Sequential = new javax.swing.JLabel();
        lbl_NumberOfTests = new javax.swing.JLabel();
        lbl_FileSize = new javax.swing.JLabel();
        lbl_BlockSize = new javax.swing.JLabel();
        cb_NumberOfTests = new javax.swing.JComboBox<>();
        cb_FileSize = new javax.swing.JComboBox<>();
        cb_BlockSize = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        RunConfiguration = new javax.swing.JPanel();
        jt_random = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jt_nr = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        testtext = new javax.swing.JTextField();
        UploadScore = new javax.swing.JPanel();
        lbl_information = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        s_name = new javax.swing.JSeparator();
        lbl_laptopmodel = new javax.swing.JLabel();
        tf_laptopmodel = new javax.swing.JTextField();
        s_laptopmodel = new javax.swing.JSeparator();
        lbl_selectDrive = new javax.swing.JLabel();
        lbl_ssd = new javax.swing.JLabel();
        rb_ssd = new javax.swing.JRadioButton();
        lbl_hdd = new javax.swing.JLabel();
        rd_hdd = new javax.swing.JRadioButton();
        lbl_selectDrive1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        lbl_BUpload = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Help = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(9, 65, 109));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 399));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });

        lbl_ConfigureTest.setBackground(new java.awt.Color(9, 65, 109));
        lbl_ConfigureTest.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        lbl_ConfigureTest.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ConfigureTest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ConfigureTest.setText("Configure Test");
        lbl_ConfigureTest.setMaximumSize(new java.awt.Dimension(40, 14));
        lbl_ConfigureTest.setMinimumSize(new java.awt.Dimension(40, 14));
        lbl_ConfigureTest.setOpaque(true);
        lbl_ConfigureTest.setPreferredSize(new java.awt.Dimension(40, 14));
        lbl_ConfigureTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ConfigureTestMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_ConfigureTestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_ConfigureTestMouseExited(evt);
            }
        });

        lbl_RunTest.setBackground(new java.awt.Color(9, 65, 109));
        lbl_RunTest.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        lbl_RunTest.setForeground(new java.awt.Color(255, 255, 255));
        lbl_RunTest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_RunTest.setText("Run Configuration");
        lbl_RunTest.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_RunTest.setOpaque(true);
        lbl_RunTest.setRequestFocusEnabled(false);
        lbl_RunTest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_RunTestMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_RunTestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_RunTestMouseExited(evt);
            }
        });

        lbl_UploadScore.setBackground(new java.awt.Color(9, 65, 109));
        lbl_UploadScore.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        lbl_UploadScore.setForeground(new java.awt.Color(255, 255, 255));
        lbl_UploadScore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_UploadScore.setText("Upload Score");
        lbl_UploadScore.setMaximumSize(new java.awt.Dimension(40, 14));
        lbl_UploadScore.setMinimumSize(new java.awt.Dimension(40, 14));
        lbl_UploadScore.setOpaque(true);
        lbl_UploadScore.setPreferredSize(new java.awt.Dimension(40, 14));
        lbl_UploadScore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_UploadScoreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_UploadScoreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_UploadScoreMouseExited(evt);
            }
        });

        lbl_Help.setBackground(new java.awt.Color(9, 65, 109));
        lbl_Help.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        lbl_Help.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Help.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Help.setText("Help");
        lbl_Help.setMaximumSize(new java.awt.Dimension(40, 14));
        lbl_Help.setMinimumSize(new java.awt.Dimension(40, 14));
        lbl_Help.setOpaque(true);
        lbl_Help.setPreferredSize(new java.awt.Dimension(40, 14));
        lbl_Help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_HelpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_HelpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_HelpMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/final_icon_2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_RunTest, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(lbl_ConfigureTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_UploadScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_Help, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(66, 66, 66))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(lbl_ConfigureTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_RunTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addComponent(lbl_UploadScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Help, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(94, 94, 94))
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(650, 400));
        jPanel2.setLayout(new java.awt.CardLayout());

        rb_RandomAccess.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_RandomAccessMouseClicked(evt);
            }
        });
        rb_RandomAccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_RandomAccessActionPerformed(evt);
            }
        });

        rb_Sequential.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rb_SequentialMouseClicked(evt);
            }
        });
        rb_Sequential.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_SequentialActionPerformed(evt);
            }
        });

        lbl_RandomAccess.setText("Random Access");

        lbl_Sequential.setText("Sequential Access");

        lbl_NumberOfTests.setText("Number of Tests");

        lbl_FileSize.setText("File Size");

        lbl_BlockSize.setText("Block Size");

        cb_NumberOfTests.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        cb_NumberOfTests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_NumberOfTestsActionPerformed(evt);
            }
        });

        cb_FileSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "64 KB", "512 bytes", "1 KB", "2 KB", "4 KB", "8 KB", "16 KB", "32 KB", "128 KB", "256 KB", "512 KB", "1 MB", "2 MB", "4 MB", "8 MB", "16 MB", "32 MB" }));
        cb_FileSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_FileSizeActionPerformed(evt);
            }
        });

        cb_BlockSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 GB", "3 GB", "5 GB" }));
        cb_BlockSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_BlockSizeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/normal.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel4MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout ConfigureTestLayout = new javax.swing.GroupLayout(ConfigureTest);
        ConfigureTest.setLayout(ConfigureTestLayout);
        ConfigureTestLayout.setHorizontalGroup(
            ConfigureTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfigureTestLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(ConfigureTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ConfigureTestLayout.createSequentialGroup()
                        .addComponent(lbl_RandomAccess)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rb_RandomAccess))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConfigureTestLayout.createSequentialGroup()
                        .addComponent(lbl_NumberOfTests)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cb_NumberOfTests, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConfigureTestLayout.createSequentialGroup()
                        .addGroup(ConfigureTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(ConfigureTestLayout.createSequentialGroup()
                                .addGroup(ConfigureTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_FileSize, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_BlockSize, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(95, 95, 95))
                            .addComponent(lbl_Sequential, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGroup(ConfigureTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ConfigureTestLayout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(cb_FileSize, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cb_BlockSize, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb_Sequential))))
                .addContainerGap(143, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ConfigureTestLayout.setVerticalGroup(
            ConfigureTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConfigureTestLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(ConfigureTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb_Sequential)
                    .addComponent(lbl_Sequential))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ConfigureTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_RandomAccess)
                    .addComponent(rb_RandomAccess))
                .addGap(18, 18, 18)
                .addGroup(ConfigureTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_NumberOfTests)
                    .addComponent(cb_NumberOfTests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ConfigureTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_FileSize)
                    .addComponent(cb_BlockSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ConfigureTestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_FileSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_BlockSize))
                .addGap(84, 84, 84))
        );

        jPanel2.add(ConfigureTest, "card2");

        jt_random.setText("jTextField2");
        jt_random.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_randomActionPerformed(evt);
            }
        });

        jTextField3.setText("Random/ Seq");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel3.setText("Nr of Tests");

        jt_nr.setText("jTextField4");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/normal.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel5MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(602, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        testtext.setText("jTextField2");
        testtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testtextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RunConfigurationLayout = new javax.swing.GroupLayout(RunConfiguration);
        RunConfiguration.setLayout(RunConfigurationLayout);
        RunConfigurationLayout.setHorizontalGroup(
            RunConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RunConfigurationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(RunConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RunConfigurationLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(RunConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jt_nr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(RunConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jt_random, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField3)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(118, 118, 118))
                    .addGroup(RunConfigurationLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(29, 29, 29)
                        .addComponent(testtext, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        RunConfigurationLayout.setVerticalGroup(
            RunConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RunConfigurationLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jt_random, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jt_nr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(RunConfigurationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(testtext, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jPanel2.add(RunConfiguration, "card2");

        lbl_information.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_information.setText("Information");

        lbl_name.setText("Name");

        tf_name.setBackground(new java.awt.Color(214, 217, 223));
        tf_name.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        tf_name.setForeground(new java.awt.Color(153, 153, 153));
        tf_name.setText("  nickname or name");
        tf_name.setBorder(null);
        tf_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_nameFocusLost(evt);
            }
        });
        tf_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nameActionPerformed(evt);
            }
        });

        lbl_laptopmodel.setText("Laptop Model");

        tf_laptopmodel.setBackground(new java.awt.Color(214, 217, 223));
        tf_laptopmodel.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        tf_laptopmodel.setForeground(new java.awt.Color(153, 153, 153));
        tf_laptopmodel.setText("  leave blank if you have a desktop");
        tf_laptopmodel.setBorder(null);
        tf_laptopmodel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_laptopmodelFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_laptopmodelFocusLost(evt);
            }
        });
        tf_laptopmodel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_laptopmodelActionPerformed(evt);
            }
        });

        lbl_selectDrive.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_selectDrive.setText("Select Drive");

        lbl_ssd.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbl_ssd.setText("SSD");
        lbl_ssd.setToolTipText("Solid State Drive");

        rb_ssd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_ssdActionPerformed(evt);
            }
        });

        lbl_hdd.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbl_hdd.setText("HDD");
        lbl_hdd.setToolTipText("Hard Disk Drive");

        rd_hdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_hddActionPerformed(evt);
            }
        });

        lbl_selectDrive1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_selectDrive1.setText("Score Result");

        jTextField1.setBackground(new java.awt.Color(214, 217, 223));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("score");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        lbl_BUpload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button_default.png"))); // NOI18N
        lbl_BUpload.setText("jLabel1");
        lbl_BUpload.setPreferredSize(new java.awt.Dimension(177, 52));
        lbl_BUpload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_BUploadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_BUploadMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_BUploadMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_BUploadMouseReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/normal.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel7MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout UploadScoreLayout = new javax.swing.GroupLayout(UploadScore);
        UploadScore.setLayout(UploadScoreLayout);
        UploadScoreLayout.setHorizontalGroup(
            UploadScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UploadScoreLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(UploadScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_name)
                    .addComponent(s_name)
                    .addComponent(lbl_laptopmodel)
                    .addComponent(s_laptopmodel)
                    .addComponent(lbl_information)
                    .addComponent(tf_laptopmodel)
                    .addComponent(tf_name)
                    .addComponent(lbl_BUpload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(UploadScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UploadScoreLayout.createSequentialGroup()
                        .addGroup(UploadScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_hdd)
                            .addComponent(lbl_ssd))
                        .addGap(47, 47, 47)
                        .addGroup(UploadScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rd_hdd)
                            .addComponent(rb_ssd))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lbl_selectDrive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(UploadScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_selectDrive1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addGap(54, 54, 54))
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        UploadScoreLayout.setVerticalGroup(
            UploadScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UploadScoreLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(UploadScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UploadScoreLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(UploadScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_ssd)
                            .addComponent(rb_ssd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(UploadScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rd_hdd)
                            .addComponent(lbl_hdd)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UploadScoreLayout.createSequentialGroup()
                        .addGroup(UploadScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(UploadScoreLayout.createSequentialGroup()
                                .addGroup(UploadScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_information)
                                    .addComponent(lbl_selectDrive)
                                    .addComponent(lbl_selectDrive1))
                                .addGap(34, 34, 34)
                                .addComponent(lbl_name)
                                .addGap(12, 12, 12))
                            .addGroup(UploadScoreLayout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)))
                        .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(s_name, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_laptopmodel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_laptopmodel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s_laptopmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(lbl_BUpload, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jPanel2.add(UploadScore, "card2");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/normal.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel6MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout HelpLayout = new javax.swing.GroupLayout(Help);
        Help.setLayout(HelpLayout);
        HelpLayout.setHorizontalGroup(
            HelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HelpLayout.setVerticalGroup(
            HelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HelpLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 349, Short.MAX_VALUE))
        );

        jPanel2.add(Help, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_RunTestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_RunTestMouseClicked
        isRunTestClicked = true;
        isConfigureTestClicked = false;
        isUploadScoreClicked = false;
        isHelpClicked = false;
        setLblColor(lbl_RunTest);
        resetLblColor(lbl_ConfigureTest);
        resetLblColor(lbl_UploadScore); 
        resetLblColor(lbl_Help);
        
        // Switch between JPanels
        ConfigureTest.setVisible(false);
        RunConfiguration.setVisible(true);
        UploadScore.setVisible(false);
        Help.setVisible(false);
        
        // Run Test Configuration with our Configuration (or default)
        if(rb_RandomAccess.isEnabled())
             jt_random.setText("Random");
        jt_nr.setText((String) cb_NumberOfTests.getSelectedItem());

    }//GEN-LAST:event_lbl_RunTestMouseClicked

    private void lbl_ConfigureTestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ConfigureTestMouseClicked
        isRunTestClicked = false;
        isConfigureTestClicked = true;
        isUploadScoreClicked = false;
        isHelpClicked = false;
        setLblColor(lbl_ConfigureTest);   
        resetLblColor(lbl_RunTest);
        resetLblColor(lbl_UploadScore);
        resetLblColor(lbl_Help);
        
        // Switch between JPanels
        ConfigureTest.setVisible(true);
        RunConfiguration.setVisible(false);
        UploadScore.setVisible(false);
        Help.setVisible(false);
    }//GEN-LAST:event_lbl_ConfigureTestMouseClicked

    private void lbl_UploadScoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_UploadScoreMouseClicked
       isRunTestClicked = false;
       isConfigureTestClicked = false;
        isUploadScoreClicked = true;
        isHelpClicked = false;
       setLblColor(lbl_UploadScore);
       resetLblColor(lbl_RunTest);
       resetLblColor(lbl_ConfigureTest);
       resetLblColor(lbl_Help);
       
        // Switch between JPanels
        ConfigureTest.setVisible(false);
        RunConfiguration.setVisible(false);
        UploadScore.setVisible(true);
        Help.setVisible(false);
    }//GEN-LAST:event_lbl_UploadScoreMouseClicked

    private void lbl_HelpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_HelpMouseClicked
        isRunTestClicked = false;
        isConfigureTestClicked = false;
        isUploadScoreClicked = false;
        isHelpClicked = true;
        setLblColor(lbl_Help);
        resetLblColor(lbl_RunTest);
        resetLblColor(lbl_ConfigureTest);
        resetLblColor(lbl_UploadScore);
        
        // Switch between JPanels
        ConfigureTest.setVisible(false);
        RunConfiguration.setVisible(false);
        UploadScore.setVisible(false);
        Help.setVisible(true);
    }//GEN-LAST:event_lbl_HelpMouseClicked

    private void lbl_RunTestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_RunTestMouseEntered
        if(isRunTestClicked == false){
            setLblHoverColor(lbl_RunTest);
         //   resetLblColor(lbl_ConfigureTest);
           // resetLblColor(lbl_UploadScore);
          //  resetLblColor(lbl_Help);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_RunTestMouseEntered

    private void lbl_ConfigureTestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ConfigureTestMouseEntered
        if(isConfigureTestClicked == false){
          //  resetLblColor(lbl_RunTest);
           // resetLblColor(lbl_UploadScore);
          //  resetLblColor(lbl_Help);
            setLblHoverColor(lbl_ConfigureTest);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_ConfigureTestMouseEntered

    private void lbl_UploadScoreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_UploadScoreMouseEntered
        if(isUploadScoreClicked == false){
         //   resetLblColor(lbl_RunTest);
          //  resetLblColor(lbl_ConfigureTest);
           // resetLblColor(lbl_Help);
            setLblHoverColor(lbl_UploadScore);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_UploadScoreMouseEntered

    private void lbl_HelpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_HelpMouseEntered
        if(isHelpClicked == false){
        //=    resetLblColor(lbl_RunTest);
          //  resetLblColor(lbl_ConfigureTest);
          //  resetLblColor(lbl_UploadScore);
            setLblHoverColor(lbl_Help);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_HelpMouseEntered

    private void lbl_RunTestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_RunTestMouseExited
        if(isConfigureTestClicked == false)
            resetLblColor(lbl_ConfigureTest);
        if(isUploadScoreClicked == false)
            resetLblColor(lbl_UploadScore);
        if(isHelpClicked == false)
            resetLblColor(lbl_Help);
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_RunTestMouseExited

    private void lbl_ConfigureTestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ConfigureTestMouseExited
        if(isRunTestClicked == false)
            resetLblColor(lbl_RunTest); 
        if(isUploadScoreClicked == false)
            resetLblColor(lbl_UploadScore);
        if(isHelpClicked == false)
            resetLblColor(lbl_Help);
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_ConfigureTestMouseExited

    private void lbl_UploadScoreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_UploadScoreMouseExited
        if(isRunTestClicked == false)
            resetLblColor(lbl_RunTest); 
        if(isConfigureTestClicked == false)
            resetLblColor(lbl_ConfigureTest);
        if(isHelpClicked == false)
            resetLblColor(lbl_Help);
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_UploadScoreMouseExited

    private void lbl_HelpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_HelpMouseExited
        if(isRunTestClicked == false)
            resetLblColor(lbl_RunTest); 
        if(isConfigureTestClicked == false)
            resetLblColor(lbl_ConfigureTest);
        if(isUploadScoreClicked == false)
            resetLblColor(lbl_UploadScore);
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_HelpMouseExited

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        if(isRunTestClicked == true){
            resetLblColor(lbl_ConfigureTest);
            resetLblColor(lbl_UploadScore);
            resetLblColor(lbl_Help);
        }
        if(isConfigureTestClicked == true){
            resetLblColor(lbl_RunTest);
            resetLblColor(lbl_UploadScore);
            resetLblColor(lbl_Help);
        }
        if(isUploadScoreClicked == true){
            resetLblColor(lbl_RunTest);
            resetLblColor(lbl_ConfigureTest);
            resetLblColor(lbl_Help);
        }
        if(isHelpClicked == true){
            resetLblColor(lbl_RunTest);
            resetLblColor(lbl_ConfigureTest);
            resetLblColor(lbl_UploadScore);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseEntered

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        if(isRunTestClicked == true){
            resetLblColor(lbl_ConfigureTest);
            resetLblColor(lbl_UploadScore);
            resetLblColor(lbl_Help);
        }
        if(isConfigureTestClicked == true){
            resetLblColor(lbl_RunTest);
            resetLblColor(lbl_UploadScore);
            resetLblColor(lbl_Help);
        }
        if(isUploadScoreClicked == true){
            resetLblColor(lbl_RunTest);
            resetLblColor(lbl_ConfigureTest);
            resetLblColor(lbl_Help);
        }
        if(isHelpClicked == true){
            resetLblColor(lbl_RunTest);
            resetLblColor(lbl_ConfigureTest);
            resetLblColor(lbl_UploadScore);
        }// TODO add your handling code here:
    }//GEN-LAST:event_formMouseEntered

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xx = evt.getX();
        xy = evt.getY();
        // TODO add your handling code here:
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-xy);
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        isRunTestClicked = false;
        isConfigureTestClicked = true;
        isUploadScoreClicked = false;
        isHelpClicked = false;
        setLblColor(lbl_ConfigureTest);   
        resetLblColor(lbl_RunTest);
        resetLblColor(lbl_UploadScore);
        resetLblColor(lbl_Help);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void cb_BlockSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_BlockSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_BlockSizeActionPerformed

    private void cb_FileSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_FileSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_FileSizeActionPerformed

    private void cb_NumberOfTestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_NumberOfTestsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_NumberOfTestsActionPerformed

    private void rb_RandomAccessMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_RandomAccessMouseClicked
        if(rb_RandomAccess.isSelected()){
           rb_Sequential.setSelected(false);
           
        }
        else{//switch to Sequential
            rb_Sequential.setSelected(true);
            rb_RandomAccess.setSelected(false);
        }
            //rb_RandomAccess.setSelected(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_RandomAccessMouseClicked

    private void rb_SequentialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rb_SequentialMouseClicked
        if(rb_Sequential.isSelected())
            rb_RandomAccess.setSelected(false);
        else{//switch to RandomAccess 
            rb_RandomAccess.setSelected(true);
            rb_Sequential.setSelected(false);
        }
            //rb_Sequential.setSelected(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_SequentialMouseClicked

    private void tf_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nameActionPerformed

    private void rd_hddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_hddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_hddActionPerformed

    private void rb_ssdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_ssdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_ssdActionPerformed

    private void tf_laptopmodelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_laptopmodelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_laptopmodelActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void tf_laptopmodelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_laptopmodelFocusGained
        lbl_laptopmodel.setForeground(new Color(24, 186, 129)); //focused -> green
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_laptopmodelFocusGained

    private void tf_laptopmodelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_laptopmodelFocusLost
        lbl_laptopmodel.setForeground(new Color(0, 0, 0)); //unfocused -> blue
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_laptopmodelFocusLost

    private void tf_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_nameFocusGained
        lbl_name.setForeground(new Color(24, 186, 129)); //focused -> green        
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nameFocusGained

    private void tf_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_nameFocusLost
        lbl_name.setForeground(new Color(0, 0, 0));  //unfocused -> blue
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nameFocusLost

    private void lbl_BUploadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_BUploadMouseEntered
        ImageIcon IB;
        IB = new ImageIcon(getClass().getResource("/images/button_hoverpsd.png"));
        lbl_BUpload.setIcon(IB);
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_BUploadMouseEntered

    private void lbl_BUploadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_BUploadMouseExited
        ImageIcon IB;
        IB = new ImageIcon(getClass().getResource("/images/button_default.png"));
        lbl_BUpload.setIcon(IB);
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_BUploadMouseExited

    private void lbl_BUploadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_BUploadMousePressed
        ImageIcon IB;
        IB = new ImageIcon(getClass().getResource("/images/button_pressed.png"));
        lbl_BUpload.setIcon(IB);
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_BUploadMousePressed

    private void lbl_BUploadMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_BUploadMouseReleased
        ImageIcon IB;
        IB = new ImageIcon(getClass().getResource("/images/button_hoverpsd.png"));
        lbl_BUpload.setIcon(IB);
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_BUploadMouseReleased

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jt_randomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_randomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_randomActionPerformed

    private void rb_RandomAccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_RandomAccessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_RandomAccessActionPerformed

    private void rb_SequentialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_SequentialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_SequentialActionPerformed

    private void jLabel4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseReleased
        ImageIcon IB;
        IB = new ImageIcon(getClass().getResource("/images/hover.png"));
        jLabel4.setIcon(IB);
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseReleased

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        ImageIcon IB;
        IB = new ImageIcon(getClass().getResource("/images/hovered.png"));
        jLabel4.setIcon(IB);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        ImageIcon IB;
        IB = new ImageIcon(getClass().getResource("/images/normal.png"));
        jLabel4.setIcon(IB);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        ImageIcon IB;
        IB = new ImageIcon(getClass().getResource("/images/hover.png"));
        jLabel4.setIcon(IB);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseEntered
                                      
    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        ImageIcon IB;
        IB = new ImageIcon(getClass().getResource("/images/hover.png"));
        jLabel5.setIcon(IB);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        ImageIcon IB;
        IB = new ImageIcon(getClass().getResource("/images/normal.png"));
        jLabel5.setIcon(IB);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        ImageIcon IB;
        IB = new ImageIcon(getClass().getResource("/images/hovered.png"));
        jLabel5.setIcon(IB);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MousePressed

    private void jLabel5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseReleased
        ImageIcon IB;
        IB = new ImageIcon(getClass().getResource("/images/hover.png"));
        jLabel5.setIcon(IB);
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseReleased

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        ImageIcon IB;
        IB = new ImageIcon(getClass().getResource("/images/hover.png"));
        jLabel6.setIcon(IB);
        // TODO add your handling code here:// TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        ImageIcon IB;
        IB = new ImageIcon(getClass().getResource("/images/normal.png"));
        jLabel6.setIcon(IB);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        ImageIcon IB;
        IB = new ImageIcon(getClass().getResource("/images/hovered.png"));
        jLabel6.setIcon(IB);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MousePressed

    private void jLabel6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseReleased
        ImageIcon IB;
        IB = new ImageIcon(getClass().getResource("/images/hover.png"));
        jLabel6.setIcon(IB);
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseReleased

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        ImageIcon IB;
        IB = new ImageIcon(getClass().getResource("/images/hover.png"));
        jLabel7.setIcon(IB);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        ImageIcon IB;
        IB = new ImageIcon(getClass().getResource("/images/normal.png"));
        jLabel7.setIcon(IB);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        ImageIcon IB;
        IB = new ImageIcon(getClass().getResource("/images/hovered.png"));
        jLabel7.setIcon(IB);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MousePressed

    private void jLabel7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseReleased
        ImageIcon IB;
        IB = new ImageIcon(getClass().getResource("/images/hover.png"));
        jLabel7.setIcon(IB);
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseReleased

    private void testtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testtextActionPerformed
      
    }//GEN-LAST:event_testtextActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    int a; String b, c, d;
                a = getReadWriteMethod();
                b = getNumberOfTests();
                c = getFileSize();
                d = getBlockSize();// TODO add your handling code here:
                String res = "ReadWriteMethod " + Integer.toString(a) + "--NrTests " + b + "--File Size " + c + "--Block Size "+ d;
                testtext.setText(res);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    
        
    public void setLblColor(JLabel lbl){
        lbl.setBackground(new Color(24, 186, 129));
        
    }
    
    public void resetLblColor(JLabel lbl){
        lbl.setBackground(new Color(9,65,109));
    }
    
    private void setLblHoverColor(JLabel lbl) {
        lbl.setBackground(new Color(6,56,94));
    }
    
    /**
     *
     * @param evt
     */
    public int testMethod(java.awt.event.MouseEvent evt) {
        isRunTestClicked = true;
        isConfigureTestClicked = false;
        isUploadScoreClicked = false;
        isHelpClicked = false;
        setLblColor(lbl_RunTest);
        resetLblColor(lbl_ConfigureTest);
        resetLblColor(lbl_UploadScore); 
        resetLblColor(lbl_Help);
        
        // Switch between JPanels
        ConfigureTest.setVisible(false);
        RunConfiguration.setVisible(true);
        UploadScore.setVisible(false);
        Help.setVisible(false);
        
        // Run Test Configuration with our Configuration (or default)
        if(rb_RandomAccess.isEnabled())
             jt_random.setText("Random");
        jt_nr.setText((String) cb_NumberOfTests.getSelectedItem());
        return 1;
    }                                        
    
    public int getReadWriteMethod(){
        if("disable".equals(rb_Sequential.getActionCommand())){
        //if(rb_RandomAccess.isEnabled() == true){
            return 1;
        }
        //if(rb_Sequential.isEnabled())
    return 0;
}

    public String getNumberOfTests(){
      return (String) cb_NumberOfTests.getSelectedItem();
    }

    public String getFileSize(){
      return (String) cb_FileSize.getSelectedItem();
    }

    public String getBlockSize(){
      return (String) cb_BlockSize.getSelectedItem();
    }
    
      /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    
   // private void setLblHoverOffColor(JLabel lbl) {
    //    lbl.setBackground(new Color(9,65,109));
   // }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ConfigureTest;
    private javax.swing.JPanel Help;
    private javax.swing.JPanel RunConfiguration;
    private javax.swing.JPanel UploadScore;
    private javax.swing.JComboBox<String> cb_BlockSize;
    private javax.swing.JComboBox<String> cb_FileSize;
    private javax.swing.JComboBox<String> cb_NumberOfTests;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jt_nr;
    private javax.swing.JTextField jt_random;
    private javax.swing.JLabel lbl_BUpload;
    private javax.swing.JLabel lbl_BlockSize;
    private javax.swing.JLabel lbl_ConfigureTest;
    private javax.swing.JLabel lbl_FileSize;
    private javax.swing.JLabel lbl_Help;
    private javax.swing.JLabel lbl_NumberOfTests;
    private javax.swing.JLabel lbl_RandomAccess;
    private javax.swing.JLabel lbl_RunTest;
    private javax.swing.JLabel lbl_Sequential;
    private javax.swing.JLabel lbl_UploadScore;
    private javax.swing.JLabel lbl_hdd;
    private javax.swing.JLabel lbl_information;
    private javax.swing.JLabel lbl_laptopmodel;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_selectDrive;
    private javax.swing.JLabel lbl_selectDrive1;
    private javax.swing.JLabel lbl_ssd;
    private javax.swing.JRadioButton rb_RandomAccess;
    private javax.swing.JRadioButton rb_Sequential;
    private javax.swing.JRadioButton rb_ssd;
    private javax.swing.JRadioButton rd_hdd;
    private javax.swing.JSeparator s_laptopmodel;
    private javax.swing.JSeparator s_name;
    private javax.swing.JTextField testtext;
    private javax.swing.JTextField tf_laptopmodel;
    private javax.swing.JTextField tf_name;
    // End of variables declaration//GEN-END:variables

    

}
